// GENERATED BY `make types` FROM THE PYDANTIC MODELS IN
// `src/election_guide/rendering/payload.py`. DO NOT EDIT BY HAND.
//
// The embedded JSON payload's shape, as the client consumes it
// (docs/FRONTEND.md, The data contract). `tsc --noEmit --checkJs` holds every
// client module to these declarations and
// `tests/test_client_payload_types.py` fails when this file and the models
// disagree, so a Python model change that breaks a client consumer fails
// `make check` rather than the published page.
//
// Emitted by json-schema-to-typescript 15.0.4, with `export` stripped so the
// names stay ambient.

/**
 * A grade the client's own scoring engine can resolve to.
 *
 * No payload field carries this: the client computes it. It is declared here
 * anyway because the grade strings have a Python origin
 * (`scoring/models.py`), and docs/FRONTEND.md's Shared names section allows
 * exactly one generator for such a value. Declaring it from the Python
 * definition keeps the client's `ComputedGrade` and the audited engine's
 * `Grade` from drifting apart.
 */
type ComputedGrade = "TIED" | "Insufficient" | "A+" | "A" | "B" | "C" | "D";

/**
 * The complete client type surface, in one root.
 *
 * Nothing serializes this model; each page publishes one of its members. It
 * exists so the schema-to-types generator emits every declaration from one
 * document, in one pass, into one committed file.
 */
interface ClientPayloadTypes {
  guide_page: GuidePayload;
  sources_page: SourcesPayload;
  comparisons_page: ComparisonsPayload;
  computed_grade: ComputedGrade;
}
/**
 * The endorsements guide's payload.
 */
interface GuidePayload {
  schema_version: "1.0";
  data_version: string;
  panel_id: string;
  panel_hash: string;
  policy: LensPolicy;
  scoring: LensScoring;
  categories: LensCategory[];
  sources: LensSource[];
  races: RaceDisplay[];
  filter_scopes: FilterScope[];
  sources_page_path: string;
  personalization: PersonalizationContract | null;
}
/**
 * The slice of the release policy the fragment codec needs.
 */
interface LensPolicy {
  maximum_url_characters: number;
}
/**
 * The scoring identity a shared link is validated against.
 */
interface LensScoring {
  configuration_id: string;
}
/**
 * A selectable grouping, addressed by code.
 */
interface LensCategory {
  code: string;
  label: string;
  selectable: boolean;
  panel_role: "tallying" | "comparison";
  member_source_codes: string[];
}
/**
 * One panel source, addressed by code.
 *
 * A comparison source is published even though nothing selects it any more
 * (issue 124): the codec identifies a pre-removal link's comparison token by
 * the published role, and must see that role to ignore the token rather than
 * reject the whole link.
 */
interface LensSource {
  code: string;
  name: string;
  panel_role: "consensus" | "comparison";
  selectable: boolean;
}
/**
 * The audited presentation of one race that client code must be able to
 * reproduce or restore.
 *
 * Every field here was previously read back out of the server-rendered
 * dialog. The document's rule is the opposite (The data contract: the DOM is
 * write-only projection), and its Cross-language mirrors section prefers
 * carrying a computed value over maintaining a second implementation of the
 * logic that computes it — so the audited candidate labels, the audited
 * candidate order, and the audited accessible summary are published here.
 */
interface RaceDisplay {
  race_id: string;
  race_label: string;
  candidates: RaceCandidateDisplay[];
  audited_accessible_summary: string;
}
/**
 * One candidate's published identity and display label.
 */
interface RaceCandidateDisplay {
  candidate_id: string;
  label: string;
}
/**
 * One option of the guide's Ballot filter, addressed by its token.
 */
interface FilterScope {
  value: string;
  label: string;
}
/**
 * The complete versioned payload consumed by the client lens modules.
 */
interface PersonalizationContract {
  schema_version: "1.0";
  policy: PersonalizationPolicy;
  panel_id: string;
  panel_version: string;
  panel_hash: string;
  scoring: PersonalizationScoring;
  /**
   * @minItems 1
   */
  categories: [PersonalizationCategory, ...PersonalizationCategory[]];
  /**
   * @minItems 1
   */
  sources: [PersonalizationSource, ...PersonalizationSource[]];
  retired_codes: PersonalizationRetiredCode[];
  /**
   * @minItems 1
   */
  races: [PersonalizationRace, ...PersonalizationRace[]];
}
/**
 * The release policy governing whether and how a lens may run.
 */
interface PersonalizationPolicy {
  enabled: boolean;
  url_schema_version: "1";
  default_mode: "audited";
  modes: ("audited" | "sources")[];
  selection_combination: "additive_union";
  weighting: "equal";
  minimum_explicit_sources: number;
  /**
   * @minItems 1
   */
  comparison_source_codes: [string, ...string[]];
  maximum_url_characters: number;
}
/**
 * The audited scoring identity a client lens must reproduce exactly.
 */
interface PersonalizationScoring {
  configuration_id: string;
  allocation: "exact_equal_split";
  minimum_explicit_sources: number;
  /**
   * @minItems 5
   * @maxItems 5
   */
  grades: [
    PersonalizationGrade,
    PersonalizationGrade,
    PersonalizationGrade,
    PersonalizationGrade,
    PersonalizationGrade
  ];
  tie_precedes_grade: boolean;
  insufficient_precedes_ordinary_grade: boolean;
  missing_coverage_enters_denominator: boolean;
  no_endorsement_enters_denominator: boolean;
}
interface PersonalizationGrade {
  grade: "A+" | "A" | "B" | "C" | "D";
  minimum_share: string;
  minimum_explicit_sources: number | null;
}
/**
 * A selectable grouping resolved against current panel membership.
 */
interface PersonalizationCategory {
  id: string;
  code: string;
  label: string;
  selectable: boolean;
  panel_role: "tallying" | "comparison";
  member_source_codes: string[];
}
/**
 * One panel source addressed by its immutable transport code.
 */
interface PersonalizationSource {
  id: string;
  code: string;
  panel_role: "consensus" | "comparison";
  selectable: boolean;
  reporting_category_id: string;
  /**
   * @minItems 1
   */
  selection_category_ids: [string, ...string[]];
  overlap_group_ids: string[];
}
/**
 * A tombstone a client migration resolver uses to identify a withdrawn code.
 *
 * The registry accumulates every retirement across every panel a lens has
 * ever been enabled for, so the current release's list is sufficient to
 * resolve a code retired in any earlier panel version.
 */
interface PersonalizationRetiredCode {
  code: string;
  kind: "source" | "category";
  former_id: string;
  reason: string;
}
/**
 * Everything a client needs to rescore one race over a chosen subset.
 */
interface PersonalizationRace {
  race_id: string;
  /**
   * @minItems 1
   */
  eligible_source_codes: [string, ...string[]];
  cells: PersonalizationCell[];
  /**
   * @minItems 1
   */
  candidate_order: [string, ...string[]];
}
/**
 * One eligible source's exact contribution to one race.
 */
interface PersonalizationCell {
  source_code: string;
  state: "endorsement" | "multi_endorsement" | "no_endorsement" | "not_covered" | "unavailable" | "unverified";
  allocation: {
    [k: string]: string;
  };
  confidence_warning: boolean;
}
/**
 * The standalone sources editor's payload.
 *
 * A selection editor only: it never scores anything, so it publishes no
 * personalization contract and no race display data.
 */
interface SourcesPayload {
  schema_version: "1.0";
  data_version: string;
  panel_id: string;
  panel_hash: string;
  policy: LensPolicy;
  scoring: LensScoring;
  categories: LensCategory[];
  sources: LensSource[];
  guide_path: string;
  tree: SourcesTreeCategory[];
}
/**
 * One selectable category on the sources page, with its rows.
 */
interface SourcesTreeCategory {
  code: string;
  label: string;
  sources: SourcesTreeSource[];
}
/**
 * One selectable source's row on the sources page.
 *
 * Everything the row renders, so the client can render it. `participation`
 * and `also_in` are carried rather than recomputed on the client:
 * docs/FRONTEND.md's Cross-language mirrors section prefers carrying a
 * computed value to maintaining a second implementation of the grammar that
 * computes it.
 */
interface SourcesTreeSource {
  code: string;
  name: string;
  evidence_url: string;
  participation: string;
  also_in: string[];
}
/**
 * The Comparisons page's payload.
 */
interface ComparisonsPayload {
  schema_version: "1.0";
  data_version: string;
  default_columns: string[];
  personalization: PersonalizationContract;
  comparisons: ComparisonsContract;
  source_labels: {
    [k: string]: string;
  };
  contested_race_ids: string[];
}
/**
 * The versioned, display-only payload consumed by comparison features.
 */
interface ComparisonsContract {
  schema_version: "1.0";
  policy: ComparisonsPolicy;
  /**
   * @minItems 1
   */
  display_index: [ComparisonDisplayRace, ...ComparisonDisplayRace[]];
}
/**
 * The release switch governing publication of the comparisons page.
 */
interface ComparisonsPolicy {
  enabled: boolean;
}
/**
 * One race's stable labels, rendered position, and audited baseline.
 */
interface ComparisonDisplayRace {
  race_id: string;
  race_label: string;
  race_type: "candidate" | "measure" | "party_office";
  section_id: string;
  section_label: string;
  section_order: number;
  race_order: number;
  candidate_names: {
    [k: string]: string;
  };
  measure_response_labels: {
    [k: string]: string;
  };
  baseline: ComparisonBaseline;
}
/**
 * The audited all-sources result copied verbatim from published consensus.
 */
interface ComparisonBaseline {
  leading_pick_ids: string[];
  share: string | null;
  explicit_source_count: number;
}
